// import { iniciativaModel, totales, bolsaHoras } from './iniciativa-model';

// export const INICIATIVAS_MOCK: iniciativaModel[] = [
//   {
//     id: 1,
//     nombre: 'Modernización Portal Web',
//     fechaAprobada: new Date('2026-01-15'),
//     estado: { idEstado: 2, descripcion: 'En Desarrollo' },
//     manDayReserva: 45,
//     horasReservadas: 360,
//     manDayConsumidos: 20,
//     horasConsumidas: 160,
//     manDayAprobadasDisponibles: 25,
//     horasAprobadasDisponibles: 200,
//   },
//   {
//     id: 2,
//     nombre: 'Implementación CRM',
//     fechaAprobada: new Date('2025-11-20'),
//     estado: { idEstado: 3, descripcion: 'Completado' },
//     manDayReserva: 60,
//     horasReservadas: 480,
//     manDayConsumidos: 58,
//     horasConsumidas: 464,
//     manDayAprobadasDisponibles: 2,
//     horasAprobadasDisponibles: 16,
//   },
//   {
//     id: 3,
//     nombre: 'Sistema de Inventario',
//     fechaAprobada: new Date('2025-09-01'),
//     estado: { idEstado: 1, descripcion: 'Autorizado Iniciar' },
//     manDayReserva: 30,
//     horasReservadas: 240,
//     manDayConsumidos: 0,
//     horasConsumidas: 0,
//     manDayAprobadasDisponibles: 30,
//     horasAprobadasDisponibles: 240,
//   },
//   {
//     id: 4,
//     nombre: 'Actualización Base de Datos',
//     fechaAprobada: new Date('2025-10-05'),
//     estado: { idEstado: 4, descripcion: 'HOLD' },
//     manDayReserva: 25,
//     horasReservadas: 200,
//     manDayConsumidos: 10,
//     horasConsumidas: 80,
//     manDayAprobadasDisponibles: 15,
//     horasAprobadasDisponibles: 120,
//   },
//   {
//     id: 5,
//     nombre: 'Migración a Cloud',
//     fechaAprobada: new Date('2025-12-10'),
//     estado: { idEstado: 2, descripcion: 'En Desarrollo' },
//     manDayReserva: 80,
//     horasReservadas: 640,
//     manDayConsumidos: 35,
//     horasConsumidas: 280,
//     manDayAprobadasDisponibles: 45,
//     horasAprobadasDisponibles: 360,
//   },
//   {
//     id: 6,
//     nombre: 'App Mobile iOS',
//     fechaAprobada: new Date('2025-08-05'),
//     estado: { idEstado: 5, descripcion: 'Detenido' },
//     manDayReserva: 50,
//     horasReservadas: 400,
//     manDayConsumidos: 12,
//     horasConsumidas: 96,
//     manDayAprobadasDisponibles: 38,
//     horasAprobadasDisponibles: 304,
//   },
// ];

// export const TOTALES_INICIATIVAS_MOCK: totales = {
//   mandayReservadas: 290,
//   horasReservadas: 2320,
//   manDayConsumidas: 135,
//   horasConsumidas: 1080,
//   manDayAprobadasDisponibles: 155,
//   horasAprobadasDisponibles: 1240,
//   bolsaHorasContratadas: 4000,
//   bolsaManDayContratados: 500,
//   horasDisponibles: 1000,
//   manDayDisponibles: 345,
// };

// export const BOLSAS_HORAS_MOCK: bolsaHoras[] = [
//   {
//     idBolsa: 1,
//     nombreBolsa: 'Bolsa Q1 2025',
//     fechaInicio: new Date('2025-01-01'),
//     fechaFin: new Date('2025-03-31'),
//     horasContratadas: 1000,
//     mandayContratados: 125,
//     idEstado: 1,
//     estado: { idEstado: 1, descripcion: 'Activa' },
//   },
//   {
//     idBolsa: 2,
//     nombreBolsa: 'Bolsa Q4 2024',
//     fechaInicio: new Date('2024-10-01'),
//     fechaFin: new Date('2024-12-31'),
//     horasContratadas: 800,
//     mandayContratados: 100,
//     idEstado: 2,
//     estado: { idEstado: 2, descripcion: 'Caducada' },
//   },
//   {
//     idBolsa: 3,
//     nombreBolsa: 'Bolsa Especial - Migración',
//     fechaInicio: new Date('2024-12-01'),
//     fechaFin: new Date('2025-05-31'),
//     horasContratadas: 1200,
//     mandayContratados: 150,
//     idEstado: 1,
//     estado: { idEstado: 1, descripcion: 'Activa' },
//   },
//   {
//     idBolsa: 4,
//     nombreBolsa: 'Bolsa Q2 2025',
//     fechaInicio: new Date('2025-04-01'),
//     fechaFin: new Date('2025-06-30'),
//     horasContratadas: 1000,
//     mandayContratados: 125,
//     idEstado: 3,
//     estado: { idEstado: 3, descripcion: 'Próxima a Caducar' },
//   },
// ];
