-- ============================
-- TABLAS DE ESTADOS
-- ============================

CREATE TABLE estado_iniciativa (
    id_estado INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO estado_iniciativa (descripcion) VALUES
('Autorizado Iniciar'),
('Completado'),
('Detenido'),
('En Desarrollo'),
('HOLD');


CREATE TABLE estado_bolsa (
    id_estado INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO estado_bolsa (descripcion) VALUES
('Activa'),
('Próxima a Caducar'),
('Caducada');


-- ============================
-- BOLSA HORAS
-- ============================

CREATE TABLE bolsa_horas (
    id_bolsa INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_bolsa VARCHAR(100) NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    horas_contratadas NUMERIC(10,2) NOT NULL,
    manday_contratados NUMERIC(10,2) NOT NULL,
    id_estado INTEGER NOT NULL,
    CONSTRAINT fk_bolsa_estado
        FOREIGN KEY (id_estado)
        REFERENCES estado_bolsa(id_estado)
);


-- ============================
-- INICIATIVA
-- ============================

CREATE TABLE iniciativa (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    fecha_aprobada DATE NOT NULL,
    id_estado INTEGER NOT NULL,
    manday_reservadas NUMERIC(10,2),
    horas_reservadas NUMERIC(10,2),
    manday_consumidos NUMERIC(10,2),
    horas_consumidas NUMERIC(10,2),
    manday_aprobadas_disponibles NUMERIC(10,2),
    horas_aprobadas_disponibles NUMERIC(10,2),
    CONSTRAINT fk_iniciativa_estado
        FOREIGN KEY (id_estado)
        REFERENCES estado_iniciativa(id_estado)
);


-- ============================
-- TOTALES
-- ============================

CREATE TABLE totales (
    id_totales INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manday_reservadas NUMERIC(10,2),
    horas_reservadas NUMERIC(10,2),
    manday_consumidas NUMERIC(10,2),
    horas_consumidas NUMERIC(10,2),
    manday_aprobadas_disponibles NUMERIC(10,2),
    horas_aprobadas_disponibles NUMERIC(10,2),
    bolsa_horas_contratadas NUMERIC(10,2),
    bolsa_manday_contratados NUMERIC(10,2),
    horas_disponibles NUMERIC(10,2),
    manday_disponibles NUMERIC(10,2)
);

INSERT INTO totales VALUES (DEFAULT,0,0,0,0,0,0,0,0,0,0);


-- ============================
-- PARAMETROS SISTEMA
-- ============================

CREATE TABLE parametros_sistema (
    clave VARCHAR(50) PRIMARY KEY,
    valor_num NUMERIC,
    valor_texto VARCHAR(100),
    descripcion VARCHAR(200),
    fecha_update DATE DEFAULT CURRENT_DATE
);

INSERT INTO parametros_sistema (
    clave,
    valor_num,
    descripcion
) VALUES (
    'DIAS_PREAVISO_BOLSA',
    30,
    'Días antes de la fecha fin para marcar bolsa como Próxima a Caducar'
);


-- ============================
-- FUNCION PARA RECALCULAR TOTALES
-- ============================

CREATE OR REPLACE FUNCTION recalcular_totales()
RETURNS void AS $$
BEGIN
    UPDATE totales
    SET
        manday_reservadas = (SELECT COALESCE(SUM(manday_reservadas),0) FROM iniciativa),
        horas_reservadas = (SELECT COALESCE(SUM(horas_reservadas),0) FROM iniciativa),
        manday_consumidas = (SELECT COALESCE(SUM(manday_consumidos),0) FROM iniciativa),
        horas_consumidas = (SELECT COALESCE(SUM(horas_consumidas),0) FROM iniciativa),
        manday_aprobadas_disponibles = (SELECT COALESCE(SUM(manday_aprobadas_disponibles),0) FROM iniciativa),
        horas_aprobadas_disponibles = (SELECT COALESCE(SUM(horas_aprobadas_disponibles),0) FROM iniciativa),
        bolsa_horas_contratadas = (SELECT COALESCE(SUM(horas_contratadas),0) FROM bolsa_horas),
        bolsa_manday_contratados = (SELECT COALESCE(SUM(manday_contratados),0) FROM bolsa_horas),
        horas_disponibles =
            (SELECT COALESCE(SUM(horas_contratadas),0) FROM bolsa_horas)
            - (SELECT COALESCE(SUM(horas_reservadas),0) FROM iniciativa),
        manday_disponibles =
            (SELECT COALESCE(SUM(manday_contratados),0) FROM bolsa_horas)
            - (SELECT COALESCE(SUM(manday_reservadas),0) FROM iniciativa);
END;
$$ LANGUAGE plpgsql;


-- ============================
-- TRIGGERS
-- ============================

CREATE OR REPLACE FUNCTION trg_totales_iniciativa_fn()
RETURNS TRIGGER AS $$
BEGIN
    PERFORM recalcular_totales();
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_totales_iniciativa
AFTER INSERT OR UPDATE OR DELETE
ON iniciativa
FOR EACH STATEMENT
EXECUTE FUNCTION trg_totales_iniciativa_fn();


CREATE OR REPLACE FUNCTION trg_totales_bolsa_fn()
RETURNS TRIGGER AS $$
BEGIN
    PERFORM recalcular_totales();
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_totales_bolsa
AFTER INSERT OR UPDATE OR DELETE
ON bolsa_horas
FOR EACH STATEMENT
EXECUTE FUNCTION trg_totales_bolsa_fn();


-- ============================
-- FUNCION PARA ACTUALIZAR ESTADO BOLSA
-- (Reemplazo del DBMS_SCHEDULER)
-- ============================

CREATE OR REPLACE FUNCTION actualizar_estado_bolsa()
RETURNS VOID AS $$
DECLARE
    v_activa INTEGER;
    v_proxima INTEGER;
    v_caducada INTEGER;
    v_dias_preav NUMERIC;
BEGIN
    SELECT id_estado INTO v_activa
    FROM estado_bolsa WHERE descripcion = 'Activa';

    SELECT id_estado INTO v_proxima
    FROM estado_bolsa WHERE descripcion = 'Próxima a Caducar';

    SELECT id_estado INTO v_caducada
    FROM estado_bolsa WHERE descripcion = 'Caducada';

    SELECT valor_num INTO v_dias_preav
    FROM parametros_sistema
    WHERE clave = 'DIAS_PREAVISO_BOLSA';

    UPDATE bolsa_horas
    SET id_estado = v_caducada
    WHERE fecha_fin < CURRENT_DATE
      AND id_estado = v_proxima;

    UPDATE bolsa_horas
    SET id_estado = v_proxima
    WHERE fecha_fin BETWEEN CURRENT_DATE
            AND CURRENT_DATE + v_dias_preav
      AND id_estado = v_activa;

END;
$$ LANGUAGE plpgsql;
